name = "hakobu-relay"
main = "worker.js"
compatibility_date = "2026-09-01"
workers_dev = false

[[routes]]
pattern = "hakobu.kaslauto.com"
custom_domain = true

# Created with: npx wrangler kv namespace create CODES
[[kv_namespaces]]
binding = "CODES"
id = "4d528850983246aa9e059f7d211b13f4"
